---
gateway_role_team_assignments:
- assignment_objects:
  - name: Org1
    type: organizations
  role_definition: Organization Inventory Admin
  team: TeamA
  
#gateway_role_team_assignments:
#- assignment_objects:
#  - name: IT Infrastructure and Servers Administration - dev
#    type: organizations
#  role_definition: Organization Inventory Admin
#  team: team2
  
#gateway_role_team_assignments:
#  - assignment_objects:
#      - name: MyOrg
#        type: organizations
#    role_definition: Organization Inventory Admin
#    team: team2
