---
aap_organizations:
  - name: Org1
  - name: Org2


#  - name: MyOrg
#    description: My First Organization
#  - name: Development
#    description: Development Environment Organization
#  - name: IT Infrastructure and Servers Administration - dev
#    description: testing
