controller_projects:
  - name: Demo Project
    organization: MyOrg
    scm_type: git
    scm_url: https://github.com/ansible/ansible-examples.git
    scm_branch: main
    description: Demo project for getting started
